package com.jbt.random;

import java.util.Random;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package basiclibrary;

public class Library {

    public static void main() {
         roll(5);

    }
    public static void roll (int n ){
//        def getRandomNumber(int num){
//            return random.nextInt(10**num)
//
//        }
    System.out.println("hello");
    }

}
